services:
  extra_nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: extra_nginx
    # ports: ["8088:80"]  # отладка без Diary
    restart: unless-stopped
    networks:
      - diary_net
      - extra_net
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/extra/blank || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  diary_net:
    external: true
    name: diary20_default
  extra_net:
    external: true
    name: extra_services
