FROM nginx:1.27-alpine

RUN rm /etc/nginx/conf.d/default.conf && \
    mkdir -p /usr/share/nginx/html/extra

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/
COPY html/ /usr/share/nginx/html/extra/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
