# Индекс /extra — страница со списком встроенных сервисов.

location = /extra {
    return 301 /extra/;
}

location = /extra/ {
    default_type text/html;
    alias /usr/share/nginx/html/extra/extra.html;
}
